# Generated by Django 4.1.7 on 2023-03-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='building',
            new_name='edificio',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='rooms',
            new_name='quartos',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='floors',
            new_name='andares',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='address',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='name',
            new_name='nome',
        ),
    ]
