# Generated by Django 4.1.7 on 2023-03-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_apartment_renter_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='apartment',
            new_name='apartamento',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='renter',
            new_name='locador',
        ),
    ]
