# Generated by Django 4.1.7 on 2023-03-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_apartment_rental_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
